# DEVELOPMENT Backend / Django Docker File
# Setup Django backend
FROM python:3.12-alpine
WORKDIR /app/backend
ENV PYTHONUNBUFFERED=1

# Install dependencies for MySQL client and other necessary build tools
COPY backend/requirements.txt .
RUN apk update && \
    apk add --no-cache \
    build-base \
    mariadb-dev \
    pkgconfig \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    # Remove unnecessary packages to reduce image size
    && apk del build-base \
    # Clean up APK cache
    && rm -rf /var/cache/apk/*

# Ensure the logs directory exists in the container
RUN mkdir -p /backend/logs

# Expose port if needed (e.g., for Django app)
EXPOSE 8000

# Define the command to run the Django app in development mode 
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]