# Generated by Django 5.1.3 on 2025-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0002_emailopportunity_job_search__user_id_7c5fdd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
