# Generated by Django 5.1.3 on 2025-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_alter_jobposting_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='technology_string',
            field=models.CharField(blank=True, default='', max_length=1028),
        ),
    ]
