# Generated by Django 5.1.3 on 2026-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_alter_jobposting_technology_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('application_source', 'Application Source'), ('posting_status', 'Posting Status'), ('employment_type', 'Employment Type'), ('location_type', 'Location Type'), ('recruitment_stage', 'Recruitment Stage')], db_index=True, help_text='Logical grouping for dropdown values', max_length=50)),
                ('name', models.CharField(help_text='Display name shown in the UI', max_length=100)),
                ('sort_order', models.FloatField(default=0, help_text='Controls display order (supports decimals like 2.5)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is selectable in the UI')),
            ],
            options={
                'verbose_name': 'Dropdown Option',
                'verbose_name_plural': 'Dropdown Options',
                'db_table': 'dropdown_options',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='dropdown_op_categor_e2c47a_idx')],
            },
        ),
    ]
