# Generated by Django 5.1.3 on 2026-04-25 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0005_dropdownoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownoption',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DashboardReportSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short label (e.g., 'Overall', 'Pathrise Method')", max_length=100)),
                ('start_date', models.DateField(help_text='Start date (inclusive)')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date (leave blank for single-day stats)', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_report_segments',
                'ordering': ['start_date'],
            },
        ),
    ]
