# Generated by Django 5.1.3 on 2026-04-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0006_dropdownoption_user_dashboardreportsegment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dropdownoption',
            new_name='job_search__categor_00386e_idx',
            old_name='dropdown_op_categor_e2c47a_idx',
        ),
        migrations.AlterModelTable(
            name='dropdownoption',
            table='job_search_dropdown_options',
        ),
    ]
