# Generated by Django 5.1.3 on 2026-04-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0007_rename_dropdown_op_categor_e2c47a_idx_job_search__categor_00386e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboardreportsegment',
            table='job_search_dashboard_report_segments',
        ),
    ]
