# Generated by Django 4.2.6 on 2024-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(max_length=64)),
                ('recruiter_company', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=128)),
                ('opportunity_status', models.CharField(max_length=24)),
                ('job_description', models.TextField()),
            ],
        ),
    ]
