# Generated by Django 4.2.6 on 2024-08-21 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(default='', max_length=64)),
                ('site_name', models.CharField(default='', max_length=64)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='emailopportunity',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailopportunity',
            name='email_received_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emailopportunity',
            name='employment_type',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='emailopportunity',
            name='job_duration',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='emailopportunity',
            name='location_city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='emailopportunity',
            name='location_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailopportunity',
            name='job_description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=64)),
                ('posting_title', models.CharField(default='', max_length=128)),
                ('posting_url', models.CharField(default='', max_length=256)),
                ('posting_location_type', models.CharField(default='', max_length=32)),
                ('posting_location_city', models.CharField(default='', max_length=64)),
                ('job_description', models.TextField()),
                ('job_site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_search.jobsite')),
            ],
        ),
    ]
