# Generated by Django 4.2.6 on 2024-08-21 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0002_jobsite_emailopportunity_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='posting_location_city',
            new_name='location_city',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='posting_location_type',
            new_name='location_type',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='headline',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='resume_updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
