# Generated by Django 4.2.6 on 2024-10-01 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_rename_posting_location_city_jobposting_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applied_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='pay_range',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='rejected_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='technology_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='technology_string',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='github_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='project_site_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='resume_format',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='site_password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
