# Generated by Django 4.2.6 on 2024-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_jobposting_applied_at_jobposting_employment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='posting_url',
            new_name='posting_url_full',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_scan_info',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='outreach_info',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_application_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_password',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_url_domain',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='rejected_after_stage',
            field=models.CharField(default='', max_length=32),
        ),
    ]
