# Generated by Django 4.2.6 on 2024-10-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0006_alter_jobsite_site_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_scan_info',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='outreach_info',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_application_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_password',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='technology_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='technology_string',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
