# Generated by Django 4.2.6 on 2024-10-03 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0007_alter_jobposting_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='applied_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='interviewed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='rejected_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
