# Generated by Django 5.1.3 on 2024-11-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0009_usersettings_jobposting_time_spent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posting_application_questions',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='technology_stack',
        ),
        migrations.AlterField(
            model_name='emailopportunity',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='emailopportunity',
            name='job_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='emailopportunity',
            name='opportunity_status',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='interviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_scan_info',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='outreach_info',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_password',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_url_full',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='technology_string',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='time_spent',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='site_password',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
